version: '3.9'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENV=dev
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
